services:
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "${NGINX_HTTP_PORT:-80}:80"
      - "${NGINX_HTTPS_PORT:-443}:443"
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./templates:/etc/nginx/templates
      - ./index.html:/usr/share/nginx/html/index.html:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      # - ./logs:/var/log/nginx
    networks:
      - monitors
    extra_hosts:
      - "host.docker.internal:host-gateway"  # ホストへのアクセス用
    environment:
      - NETDATA_PORT=${NETDATA_PORT}
      - DOZZLE_PORT=8080
      - R2MANAGER_PORT=${R2MANAGER_PORT}
      - SUB_DOMAIN=${SUB_DOMAIN}
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "10"
        compress: "true"


networks:
  monitors:
    name: monitors_network
    driver: bridge
